---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)

library(p8105.datasets)
```

```{r}
# Focus on INSTACART data.

data("instacart")


protein = 
  instacart |> 
  filter(department == "dairy eggs") |>
  select(order_id, user_id, reordered, order_dow, order_hour_of_day, days_since_prior_order, product_name, aisle, department)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Scatterplot showing oder numbers against each aisle in "dairy eggs" department

```{r}
protein |>
  group_by(aisle) |>
  summarize(n=n()) |>
  mutate(aisle = fct_reorder(aisle,n))|>
  plot_ly(x = ~n, y = ~aisle,type = "scatter", mode = "markers") |>
  layout(xaxis = list(title = "Order Numbers"), yaxis = list(title = "Aisle"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Bar plot showing the reorder rate for different cheeses

```{r}
protein |>
  filter(str_detect(aisle, "cheese.$") | str_detect(aisle, "cheese$"))|>
  group_by(aisle,reordered) |>
  summarize(n=n()) |>
  pivot_wider(names_from = reordered,
             values_from = n) |>
  rename(first_order = '0',
         re_order = '1') |>
  mutate(perc = re_order/(first_order + re_order)) |>
  mutate(aisle = fct_reorder(aisle,perc))|>
  plot_ly(y = ~perc, color = ~aisle, type = "bar", colors = "viridis") |>
  layout(xaxis = list(title = "Cheese Category"), yaxis = list(title = "Reorder rate"))
```

### Box plot showing the distribution of order hour within a day for each aisle

```{r}
protein |> 
  plot_ly(y = ~order_hour_of_day, color = ~aisle, type = "box", colors = "viridis")
```

### Density plot showing the distribution of order hour within a day for each aisle

```{r}
protein |> 
  group_by(aisle, order_hour_of_day) |>
  summarise(n = n()) |>
  plot_ly(x = ~order_hour_of_day, y = ~n, color = ~aisle, type = 'scatter', mode = 'lines', fill = 'tozeroy', colors = "viridis")
```


```{r, eval= FALSE}
rmarkdown::render("dashboard.Rmd", output_format = "flexdashboard::flex_dashboard")
```
