---
title: "plotly"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
      
---

```{r}
library(tidyverse)
library(plotly)

library(p8105.datasets)
library(flexdashboard)
```



Focus on NYC Airbnb data.

```{r}
data("nyc_airbnb")


nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```


```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```

let's make a boxplot
```{r}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

let's make a bar pllot

```{r}
nyc_airbnb |>
  count(neighbourhood)|>
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```




## ggplotly

```{r}
ggp_scatter = 
  nyc_airbnb |>
  ggplot(aes(x =lat, y = long, color = price))+
  geom_point(alpha =.5)


ggplotly(ggp_scatter)
```
not to do in very often, the quality of the plot is not good.

```{r, eval= FALSE}
rmarkdown::render("plotly.Rmd", output_format = "flexdashboard::flex_dashboard")
```


